removed GNU getopt requirement

diff --git a/tools/poly-build-heap b/tools/poly-build-heap
--- a/tools/poly-build-heap
+++ b/tools/poly-build-heap
@@ -2,51 +2,86 @@
 
 PRG="$(basename "$0")"
 
-OPTS=`getopt -o hpo: --long help,project,ouptut: -n "${PRG}" -- "$@"`
-if [ $? != 0 ] ; then echo "error when parsing command line options ..." >&2 ; exit 1 ; fi
-eval set -- "$OPTS"
+# OPTS=`getopt -o hpo: --long help,project,ouptut: -n "${PRG}" -- "$@"`
+# if [ $? != 0 ] ; then echo "error when parsing command line options ..." >&2 ; exit 1 ; fi
+# eval set -- "$OPTS"
+
+# usage () {
+#   echo "usage: ${PRG} <file>"
+#   echo "  where <file> is the SML file to be used."
+
+#   echo "OPTIONS"
+#   echo "-h --help           print this message"
+#   echo "-p --project        set if <file> uses PolyML.Project"
+#   echo "-o --output <heap>  set the name of the generated heap to <heap>"
+# }
+
+# while true
+# do
+#     case "$1" in
+#     -h|--help)
+#       usage
+#       exit 0
+#     ;;
+#     -o|--output)
+#       HEAP="$2"
+#       shift 2
+#     ;;
+#     -p|--project)
+#       PROJECT=1
+#       shift 1
+#     ;;
+#     --)
+#       shift
+#       break
+#     ;;
+#     *)
+#       echo "Internal error!"
+#       exit 1
+#     ;;
+#     esac
+# done
+
+# if [[ $# != 1 ]]
+# then
+#   usage >&2
+#   exit 1
+# fi
 
 usage () {
   echo "usage: ${PRG} <file>"
   echo "  where <file> is the SML file to be used."
 
   echo "OPTIONS"
-  echo "-h --help           print this message"
-  echo "-p --project        set if <file> uses PolyML.Project"
-  echo "-o --output <heap>  set the name of the generated heap to <heap>"
+  echo "-h            print this message"
+  echo "-p            set if <file> uses PolyML.Project"
+  echo "-o <heap>     set the name of the generated heap to <heap>"
 }
 
-while true
-do
-    case "$1" in
-    -h|--help)
+
+while getopts "hpo:" opt; do
+  case $opt in
+    h)
       usage
       exit 0
     ;;
-    -o|--output)
-      HEAP="$2"
-      shift 2
-    ;;
-    -p|--project)
+    p)
       PROJECT=1
-      shift 1
     ;;
-    --)
-      shift
-      break
+    o)
+      HEAP=$OPTARG
     ;;
-    *)
-      echo "Internal error!"
+    \?)
+      usage >&2
       exit 1
     ;;
-    esac
+  esac
 done
+shift $((OPTIND-1))
 
-if [[ $# != 1 ]]
-then
-  usage >&2
-  exit 1
-fi
+#echo $@
+
+FILE="$1"
 
 TOOLS_DIR="$(cd "$(dirname $0)"; pwd)";
 POLYML_HOME="$($TOOLS_DIR/findpoly.sh)"
@@ -56,14 +91,19 @@ if [ "$POLYML_HOME" == "" ]; then
 fi
 POLY="$POLYML_HOME/bin/poly"
 
-FILE="$1"
+#FILE="$1"
 if [[ $HEAP == "" ]]; then HEAP="${FILE%%.*}.heap"; fi
 PROJECT_MAGIC=""
 if [[ $PROJECT ]]; then
   PROJECT_MAGIC="PolyML.Project.ensure_at_latest_heap ();"
 fi
 
-BUILDFILE="$(mktemp --tmpdir tmp.XXXXXXXXXX.ML)"
+if [ "$TMPDIR" == "" ]; then
+  BUILDFILE="$(mktemp --tmpdir tmp.XXXXXXXXXX.ML)"
+else
+  BUILDFILE="$(mktemp $TMPDIR/tmp.XXXXXXXXXX.ML)"
+fi
+
 cat > "$BUILDFILE" <<- EOF
 val _ = PolyML.Compiler.printDepth := 0;
 val _ = PolyML.exception_trace (fn () => PolyML.use "${FILE}")
diff --git a/tools/polyc b/tools/polyc
--- a/tools/polyc
+++ b/tools/polyc
@@ -2,61 +2,101 @@
 
 PRG="$(basename "$0")"
 
-OPTS=`getopt -o hto:m:l: --long help,top-level,ouptut:,main:,load: -n "${PRG}" -- "$@"`
-if [ $? != 0 ] ; then echo "error when parsing command line options ..." >&2 ; exit 1 ; fi
-eval set -- "$OPTS"
+# OPTS=`getopt -o hto:m:l: --long help,top-level,ouptut:,main:,load: -n "${PRG}" -- "$@"`
+# if [ $? != 0 ] ; then echo "error when parsing command line options ..." >&2 ; exit 1 ; fi
+# eval set -- "$OPTS"
+
+# usage () {
+# 	echo "usage: ${PRG} <file>"
+# 	echo "  where <file> is the SML file to be used."
+# 	echo
+# 	echo "OPTIONS"
+# 	echo "-h --help        print this message"
+# 	echo "-m --main m      use the ML function 'm' as main-function"
+# 	echo "-o --output b    set the name of the generated binary to 'b'"
+# 	echo "-t --top-level   build custom top-level"
+# 	echo "-l --load <heap> load <heap> before using <file>"
+# }
+
+# while true
+# do
+# 	case "$1" in
+# 		-h|--help)
+# 			usage
+# 			exit 0
+# 		;;
+# 		-o|--output)
+# 			PROG="$2"
+# 			shift 2
+# 		;;
+# 		-m|--main)
+# 			MAIN="$2"
+# 			shift 2
+# 		;;
+# 		-t|--top-level)
+# 			TOP=1
+# 			shift 1
+# 		;;
+# 		-l|--load)
+# 			HEAP="$2"
+# 			shift 2
+# 		;;
+# 		--)
+# 			shift
+# 			break
+# 		;;
+# 		*)
+# 			echo "Internal error!"
+# 			exit 1
+# 		;;
+# 	esac
+# done
+
+# if [[ $# != 1 ]]
+# then
+# 	usage >&2
+# 	exit 1
+# fi
 
 usage () {
 	echo "usage: ${PRG} <file>"
 	echo "  where <file> is the SML file to be used."
 	echo
 	echo "OPTIONS"
-	echo "-h --help        print this message"
-	echo "-m --main m      use the ML function 'm' as main-function"
-	echo "-o --output b    set the name of the generated binary to 'b'"
-	echo "-t --top-level   build custom top-level"
-	echo "-l --load <heap> load <heap> before using <file>"
+	echo "-h          print this message"
+	echo "-t          build custom top-level"
+	echo "-m <main>   use the ML function <main> as main-function"
+	echo "-o <bin>    set the name of the generated binary to <bin>"
+	echo "-l <heap>   load <heap> before using <file>"
 }
 
-while true
+while getopts "htm:o:l:" opt
 do
-	case "$1" in
-		-h|--help)
+	case $opt in
+		h)
 			usage
 			exit 0
 		;;
-		-o|--output)
-			PROG="$2"
-			shift 2
+		o)
+			PROG="$OPTARG"
 		;;
-		-m|--main)
-			MAIN="$2"
-			shift 2
+		m)
+			MAIN="$OPTARG"
 		;;
-		-t|--top-level)
+		t)
 			TOP=1
-			shift 1
 		;;
-		-l|--load)
-			HEAP="$2"
-			shift 2
+		l)
+			HEAP="$OPTARG"
 		;;
-		--)
-			shift
-			break
-		;;
-		*)
-			echo "Internal error!"
-			exit 1
-		;;
-	esac
+    \?)
+      usage >&2
+      exit 1
+    ;;
+  esac
 done
+shift $((OPTIND-1))
 
-if [[ $# != 1 ]]
-then
-	usage >&2
-	exit 1
-fi
 
 TOOLS_DIR="$(cd "$(dirname $0)"; pwd)";
 POLYML_HOME="$($TOOLS_DIR/findpoly.sh)"
@@ -88,7 +128,12 @@ case "$(uname -s 2>/dev/null)" in
 		;;
 esac
 
-BUILDFILE="$(mktemp --tmpdir tmp.XXXXXXXXXX.ML)"
+if [ "$TMPDIR" == "" ]; then
+  BUILDFILE="$(mktemp --tmpdir tmp.XXXXXXXXXX.ML)"
+else
+  BUILDFILE="$(mktemp $TMPDIR/tmp.XXXXXXXXXX.ML)"
+fi
+
 echo "val _ = PolyML.Compiler.printDepth := 0;" > "$BUILDFILE"
 
 if [[ $HEAP != "" ]]; then
