fixed polyml-toplevel to run on BSD

diff --git a/tools/polyml-toplevel b/tools/polyml-toplevel
--- a/tools/polyml-toplevel
+++ b/tools/polyml-toplevel
@@ -2,45 +2,75 @@
 
 PRG="$(basename "$0")"
 
-OPTS=`getopt -o hl:w: --long help,load:,wrapper: -n "${PRG}" -- "$@"`
-if [ $? != 0 ] ; then echo "error when parsing command line options ..." >&2 ; exit 1 ; fi
-eval set -- "$OPTS"
+# OPTS=`getopt -o hl:w: --long help,load:,wrapper: -n "${PRG}" -- "$@"`
+# if [ $? != 0 ] ; then echo "error when parsing command line options ..." >&2 ; exit 1 ; fi
+# eval set -- "$OPTS"
+
+# usage () {
+# 	echo "usage: ${PRG} [opts] [-- [polyopts]]"
+# 	echo "Runs an interactive Poly/ML session, wrapped in rlwrap or similar"
+# 	echo
+# 	echo "OPTIONS"
+# 	echo "  -h --help              print this message"
+# 	echo "  -l --load <heap>       load the initial state store in <heap>"
+# 	echo "  -w --wrapper <wrapper> use the wrapper <wrapper>"
+# }
+
+# while true
+# do
+# 	case "$1" in
+# 		-h|--help)
+# 			usage
+# 			exit 0
+# 		;;
+# 		-l|--load)
+# 			HEAP="$2"
+# 			shift 2
+# 		;;
+# 		-w|--wrapper)
+# 			WRAPPER="$2"
+# 			shift 2
+# 		;;
+# 		--)
+# 			shift
+# 			break
+# 		;;
+# 		*)
+# 			echo "Internal error!"
+# 			exit 1
+# 		;;
+# 	esac
+# done
 
 usage () {
 	echo "usage: ${PRG} [opts] [-- [polyopts]]"
 	echo "Runs an interactive Poly/ML session, wrapped in rlwrap or similar"
 	echo
 	echo "OPTIONS"
-	echo "  -h --help              print this message"
-	echo "  -l --load <heap>       load the initial state store in <heap>"
-	echo "  -w --wrapper <wrapper> use the wrapper <wrapper>"
+	echo "  -h             print this message"
+	echo "  -l <heap>      load the initial state store in <heap>"
+	echo "  -w <wrapper>   use the wrapper <wrapper>"
 }
 
-while true
-do
-	case "$1" in
-		-h|--help)
-			usage
-			exit 0
-		;;
-		-l|--load)
-			HEAP="$2"
-			shift 2
-		;;
-		-w|--wrapper)
-			WRAPPER="$2"
-			shift 2
-		;;
-		--)
-			shift
-			break
-		;;
-		*)
-			echo "Internal error!"
-			exit 1
-		;;
-	esac
+while getopts "hl:w:" opt; do
+  case $opt in
+    h)
+      usage
+      exit 0
+    ;;
+    l)
+      HEAP="$OPTARG"
+    ;;
+    w)
+      WRAPPER="$OPTARG"
+    ;;
+    \?)
+      usage >&2
+      exit 1
+    ;;
+  esac
 done
+shift $((OPTIND-1))
 
 TOOLS_DIR="$(cd "$(dirname $0)"; pwd)";
 POLYML_HOME="$($TOOLS_DIR/findpoly.sh)"
@@ -50,7 +80,12 @@ if [ "$POLYML_HOME" == "" ]; then
 fi
 POLY="$POLYML_HOME/bin/poly"
 
-PRE_USE="$(mktemp --tmpdir tmp.XXXXXXXXXX.ML)"
+if [ "$TMPDIR" == "" ]; then
+  PRE_USE="$(mktemp --tmpdir tmp.XXXXXXXXXX.ML)"
+else
+  PRE_USE="$(mktemp $TMPDIR/tmp.XXXXXXXXXX.ML)"
+fi
+
 echo "val _ = PolyML.Compiler.printDepth := 0;" > "$PRE_USE"
 if [[ $HEAP != "" ]]; then
 	cat >> "$PRE_USE" <<- EOF
